/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import modelo.PedidoComprobante;
import dao.PedidoComprobanteDAO;

public class pedidoComprobanteForm extends javax.swing.JFrame {

    /**
     * Creates new form pedidoCliente
     */
    JPanel tabla = new JPanel();
    int id_PC;
    PedidoComprobanteDAO daoPC = new PedidoComprobanteDAO();
    PedidoComprobante prod = new PedidoComprobante();
    DefaultTableModel modelo = new DefaultTableModel();
    public pedidoComprobanteForm() {
        initComponents();
        listar();
        this.setLocationRelativeTo(null);
    }
    void listar(){
        List<PedidoComprobante> lista = daoPC.listar();
        modelo = (DefaultTableModel)tablaPC.getModel();
        Object[] ob= new Object[7];
        for (int i = 0; i < lista.size(); i++) {
            ob[0]=lista.get(i).getId_PC();
            ob[1]=lista.get(i).getPrePedC();
            ob[2]=lista.get(i).getCantPedCli();
            ob[3]=lista.get(i).getDesc();
            ob[4]=lista.get(i).getFecEmi();
            ob[5]=lista.get(i).getId_Cli();
            ob[6]=lista.get(i).getId_Usua();
            //Mostramos el nombre de la tabla de CategoriaProductos
            ob[7]=lista.get(i).getNomCliente();
            modelo.addRow(ob);
        }
        tablaPC.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoPC = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPC = new javax.swing.JTable();
        txtConsultaPedCliente = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cboEmpleado = new javax.swing.JComboBox<>();
        txtFechaPedido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        cboCliente = new javax.swing.JComboBox<>();
        btnEliminar = new javax.swing.JButton();
        btnInsertar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnEmpleado = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnCliente = new javax.swing.JButton();
        txtPrecio = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtDescuento = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtProducto = new javax.swing.JTextField();
        btnProductos = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        jLabel7.setText("PEDIDO CLIENTE");

        tablaPC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Pedido Cliente", "Empleado", "ID Cliente", "Fecha Pedido", "Producto", "Cantidad", "Precio 1"
            }
        ));
        tablaPC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPCMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaPC);

        jButton5.setText("BOLETA");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel2.setText("Empleado");

        jLabel3.setText("ID Cliente");

        jLabel4.setText("Fecha de Pedido");

        cboEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "1", "2" }));

        jLabel6.setText("Cantidad");

        jLabel11.setText("1-Precio S/.");

        cboCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "200", "204", "206", "208" }));

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/eliminar2.png"))); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnInsertar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnInsertar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/insertar.png"))); // NOI18N
        btnInsertar.setText("INSERTAR");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        btnActualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/actualizar.png"))); // NOI18N
        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnNuevo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/limpiar.png"))); // NOI18N
        btnNuevo.setText("NUEVO");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnEmpleado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/mostrar.png"))); // NOI18N
        btnEmpleado.setText("EMPLEADO");
        btnEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadoActionPerformed(evt);
            }
        });

        btnConsultar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/buscar.png"))); // NOI18N
        btnConsultar.setText("CONSULTAR");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/mostrar.png"))); // NOI18N
        btnCliente.setText("CLIENTE");
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });

        jLabel12.setText("Desc.");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/regresar.png"))); // NOI18N
        jButton1.setText("REGRESAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Productos");

        btnProductos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/mostrar.png"))); // NOI18N
        btnProductos.setText("PRODUCTOS");
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("SimSun", 3, 14)); // NOI18N
        jLabel8.setText("DULCE TENTACIÓN");

        javax.swing.GroupLayout fondoPCLayout = new javax.swing.GroupLayout(fondoPC);
        fondoPC.setLayout(fondoPCLayout);
        fondoPCLayout.setHorizontalGroup(
            fondoPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoPCLayout.createSequentialGroup()
                .addGroup(fondoPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoPCLayout.createSequentialGroup()
                        .addGroup(fondoPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fondoPCLayout.createSequentialGroup()
                                .addGap(267, 267, 267)
                                .addComponent(jLabel7))
                            .addGroup(fondoPCLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(fondoPCLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(fondoPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fondoPCLayout.createSequentialGroup()
                                .addGroup(fondoPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(fondoPCLayout.createSequentialGroup()
                                        .addGroup(fondoPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addGap(45, 45, 45)
                                        .addGroup(fondoPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtFechaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cboEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(43, 43, 43)
                                        .addGroup(fondoPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(fondoPCLayout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(fondoPCLayout.createSequentialGroup()
                                                .addGroup(fondoPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel11)
                                                    .addComponent(jLabel6))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(fondoPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(fondoPCLayout.createSequentialGroup()
                                                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(12, 12, 12)
                                                        .addComponent(jLabel12)))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(fondoPCLayout.createSequentialGroup()
                                        .addComponent(btnConsultar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtConsultaPedCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(34, 34, 34)
                                .addGroup(fondoPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                    .addComponent(btnInsertar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnProductos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(fondoPCLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        fondoPCLayout.setVerticalGroup(
            fondoPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoPCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(12, 12, 12)
                .addGroup(fondoPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(fondoPCLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(34, 34, 34)
                        .addGroup(fondoPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(fondoPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(21, 21, 21)
                        .addGroup(fondoPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fondoPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(fondoPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtFechaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11)
                                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)))
                        .addGap(36, 36, 36)
                        .addGroup(fondoPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtConsultaPedCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnConsultar)))
                    .addGroup(fondoPCLayout.createSequentialGroup()
                        .addComponent(btnEmpleado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCliente)
                        .addGap(3, 3, 3)
                        .addComponent(btnProductos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInsertar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnActualizar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fondoPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // Bton Eliminar
        eliminar();
        JOptionPane.showMessageDialog(this, "Se eliminó Correctamente");
        limpiarTabla();
        listar();
        nuevo();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        // Bton Insertar
        insertar();
        JOptionPane.showMessageDialog(this, "Pedido Comprobante insertado Correctamente");
        limpiarTabla();
        listar();
        nuevo();
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // Bton Actulz
        actualizar();
        JOptionPane.showMessageDialog(this, "Se actualizo Correctamente");
        limpiarTabla();
        listar();
        nuevo();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // Bton Mostrar Contenido
        nuevo();
        limpiarTabla();
        listar();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadoActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "TRABAJADOR\n"+"Id - Nombre\n"+
                "1 - Pedro\n"+"2 - Roxana");
    }//GEN-LAST:event_btnEmpleadoActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // Obtener el texto ingresado por el usuario en el campo de búsqueda
        String id_PCI = txtConsultaPedCliente.getText().trim();

        // Verificar si se ha ingresado un nombre para buscar
        if (!id_PCI.isEmpty()) {
            // Limpiar la tabla antes de agregar los resultados de la búsqueda
            limpiarTabla();

            // Llamar al método buscarPorNombre y obtener la lista de resultados
            List<PedidoComprobante> resultados = daoPC.buscarPorId(id_PCI);

            // Verificar si se encontraron resultados
            if (!resultados.isEmpty()) {
                // Llenar la tabla con los resultados de la búsqueda
                modelo = (DefaultTableModel) tablaPC.getModel();
                Object[] ob = new Object[7];

                for (PedidoComprobante pc : resultados) {
                    ob[0] = pc.getId_PC();
                    ob[1] = pc.getId_Cli();
                    ob[2] = pc.getId_Usua();
                    ob[3] = pc.getFecEmi();
                    ob[4] = pc.getPrePedC();
                    ob[5] = pc.getCantPedCli();
                    ob[6] = pc.getDesc();
                    modelo.addRow(ob);
                }

                tablaPC.setModel(modelo);
            } else {
                JOptionPane.showMessageDialog(this, "No se encontraron resultados.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese un nombre para buscar.");
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "CLIENTE\n"+"Id - Nombre - Apellido\n"+ "-----------------------------\n"+
                "200 - Pedro - Gonzales\n" + "204 - Maria - Ramirez\n" + "206 - Ruth Caceres\n" + "208 - Rosa - Mendoza\n");
    }//GEN-LAST:event_btnClienteActionPerformed

    private void tablaPCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPCMouseClicked
        // TODO add your handling code here:
        int fila=tablaPC.getSelectedRow();
        if (fila == -1) {//Si es igual a -1
            JOptionPane.showMessageDialog(this, "Debe seleccionar una Fila");
        }else{
            id_PC = Integer.parseInt(tablaPC.getValueAt(fila, 0).toString());
            String prePedC = tablaPC.getValueAt(fila, 1).toString();
            String producto = tablaPC.getValueAt(fila, 2).toString();
            String cantPedCli = tablaPC.getValueAt(fila, 3).toString();
            String desc =  tablaPC.getValueAt(fila, 4).toString();    
            String fecEmi = tablaPC.getValueAt(fila, 5).toString();
            String id_Cli = tablaPC.getValueAt(fila, 6).toString();
            String id_Usua = tablaPC.getValueAt(fila, 7).toString();
            cboEmpleado.setSelectedItem(id_Usua);
            cboCliente.setSelectedItem(id_Cli);
            txtFechaPedido.setText(fecEmi);
            txtProducto.setText(producto);
            txtCantidad.setText(cantPedCli);
            txtPrecio.setText(prePedC);
            txtDescuento.setText(desc);
        }
    }//GEN-LAST:event_tablaPCMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        clientesForm mnf = new clientesForm();
        mnf.setVisible(true);
        this.hide();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        boletaForm mnf = new boletaForm();
        mnf.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "PRODUCTOS\n"+"Id - Productos\n"+ "-------------------------\n"+
                "500 - Capuccino\n");
    }//GEN-LAST:event_btnProductosActionPerformed
    
    //Metodos para los botones
    //Insertar
    void insertar(){              
        String id_Cli = cboCliente.getSelectedItem().toString();
        String id_Usua = cboEmpleado.getSelectedItem().toString();
        String fecEmi = txtFechaPedido.getText();
        String prePedC = txtPrecio.getText();
        String cantPedCli = txtCantidad.getText();
        String producto = txtProducto.getText();
        String desc = txtDescuento.getText();
        
        //Arreglo de tipo Object
        Object[] ob = new Object[7];        
        ob[0] = id_Cli;
        ob[1] = id_Usua;
        ob[2] = producto;
        ob[3] = prePedC;
        ob[4] = desc;
        ob[5] = cantPedCli;
        ob[6] = fecEmi;
        daoPC.insertar(ob);
    }
    
    //Eliminar
    void eliminar(){
        int fila =tablaPC.getSelectedRow();
        int ids=Integer.parseInt(tablaPC.getValueAt(fila, 0).toString());
        if (fila==-1){
            JOptionPane.showMessageDialog(this, "Debe seleccionar una Fila");
        }else{
            daoPC.eliminar(ids);
        }
    }
    
    //Nuevo
    void nuevo(){
        cboCliente.setSelectedItem("");
        cboEmpleado.setSelectedItem("");
        txtFechaPedido.setText("");
        txtPrecio.setText("");
        txtProducto.setText("");
        txtCantidad.setText("");
        txtDescuento.setText("");
        
    }
    
    //Actualizar
    void actualizar(){
        int Fila=tablaPC.getSelectedRow();
        if(Fila==-1){
            JOptionPane.showMessageDialog(this, "Debe seleccionar una Fila");
        }else{
            String id_Cli = cboCliente.getSelectedItem().toString();        
            String id_Usuario = cboEmpleado.getSelectedItem().toString();
            String fecEmi = txtFechaPedido.getText();
            String prePedC = txtPrecio.getText();
            String producto = txtProducto.getText();
            String cantPedCli = txtCantidad.getText();
            String desc = txtDescuento.getText();
            Object[] obj = new Object[8];       
            obj[0] = id_Cli;
            obj[1] = id_Usuario;
            obj[2] = prePedC;
            obj[3] = producto;
            obj[4] = desc;
            obj[5] = cantPedCli;
            obj[6] = fecEmi;
            obj[7] = id_PC;
            daoPC.actualizar(obj);            
        }        
    }
    
    void limpiarTabla(){
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i=i-1;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pedidoComprobanteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pedidoComprobanteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pedidoComprobanteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pedidoComprobanteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pedidoComprobanteForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEmpleado;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnProductos;
    private javax.swing.JComboBox<String> cboCliente;
    private javax.swing.JComboBox<String> cboEmpleado;
    private javax.swing.JPanel fondoPC;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaPC;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtConsultaPedCliente;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtFechaPedido;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtProducto;
    // End of variables declaration//GEN-END:variables
}
